My First R Program

1. print

In [ ]:
print("I love jonh Rayson Yatco")

cat ("R" , "program")

print(paste("A","Program"))

[1] "I love jonh Rayson Yatco"
R program[1] "A Program"

2. variables and data types

In [ ]:
myString <- "I love jonh Rayson Yatco"
print (myString)

wholeNum <- 10
floatingNum <- 9.9
isBool <- TRUE

class(wholeNum)
class(floatingNum)
class(isBool)

[1] "I love jonh Rayson Yatco"

[1] "numeric"

[1] "numeric"

[1] "logical"

3. Numerical Operators

In [ ]:
a <- 10
b <- 49

add <- b + a
sub <- b - a
mult <- b * a
div <- b / a
mod <- b %% a
Exp <- b ^ a

print(add)
print(sub)
print(mult)
print(div)
print(mod)
print(exp)

[1] 59
[1] 39
[1] 490
[1] 4.9
[1] 9
function (x)  .Primitive("exp")

4.

4. User Input

In [ ]:
name <- readline("Enter my name: ")

cat("Welcome to my domian" , name)

Enter my name: matthew
Welcome to my domian matthew

5. Decision Making

In [ ]:
grade <- 50

if (grade > 75){
  print("Passed")
}else{
  print("Failed")
}

[1] "Failed"

6. Loop

In [ ]:
for (i in 1:5){
  print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5

7. Funtion

In [ ]:
addNum <- function(a,b){
  return (a+b)
}
addNum(a,b)

[1] 59

8. Vectors

In [ ]:
grades <- c(89,78,90,68,72)

grades

mean(grades)
min(grades)
max(grades)
median(grades)
length(grades)
summary(grades)

[1] 89 78 90 68 72

[1] 79.4

[1] 68

[1] 90

[1] 78

[1] 5

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
   68.0    72.0    78.0    79.4    89.0    90.0

9. matrices

In [ ]:
A <- matrix(c(3,2,4,5,6,7), nrow=3)
A

     [,1] [,2]
[1,] 3    5
[2,] 2    6
[3,] 4    7

10. List

In [ ]:
student <- list(
  name = "Matthew",
  Course = "BSCS",
  Section = "3A",
  FavAnime = "CSM"
)

student

$name
[1] "Matthew"

$Course
[1] "BSCS"

$Section
[1] "3A"

$FavAnime
[1] "CSM"

11. Dataframe

In [ ]:
mgakakilala <- data.frame(
  name = c ("MAT","GElO","AVI"),
  course = c ("IT","ComSci","IT"),
  favAnime = c ("CSM","JJK","Death Note"),
  grades = c ("85","75","90")
)

mgakakilala

  name course favAnime   grades
1 MAT  IT     CSM        85
2 GElO ComSci JJK        75
3 AVI  IT     Death Note 90

12. write to CSV

In [ ]:
write.csv(mgakakilala,"students.csv")

13. read CSV file

In [ ]:
data <- read.csv("students.csv")